import { initSourceEngine, getSourceEngine, resolveItemStreams, listSourceProviders } from "./source-engine.js";
let initialized=false, transport=null, playerState=null;
export async function initLunoCore(){ if(initialized) return transport; const engine=initSourceEngine(); transport={sourceEngine:engine,getState:name=>name==="player"?playerState:null,dispatch:(action)=>dispatchLunoPlayerAction(action?.args?.action||action?.action||action,action?.args?.args||{})}; initialized=true; window.__LUNO_CORE__=transport; window.__LUNO_SOURCE_ENGINE__=engine; window.dispatchEvent(new CustomEvent("luno-core-ready",{detail:{core:transport,engine}})); return transport; }
export function getLunoTransport(){return transport;}
export function getLunoAddonUrls(){return[];}
export async function installLunoAddon(){throw new Error("External Stremio manifests are not part of LUNO Source Engine");}
export async function loadMetaDetails(item,videoId=""){ if(!initialized) await initLunoCore(); const streams=await resolveItemStreams(item,{videoId}); playerState={stream:streams.length===1?{type:"Ready",content:streams[0].stream}:null,streams:streams.map(entry=>({content:{type:"Ready",content:[entry.stream]},request:entry.request,addon:entry.addon||null})),metaStreams:streams.map(entry=>({content:{type:"Ready",content:[entry.stream]},request:entry.request,addon:entry.addon||null})),libraryItem:{state:{videoId:videoId||item?.videoId||""}}}; return playerState; }
export async function loadLunoPlayer(stream){ const value=stream?.url||stream?.streamingUrl||stream?.externalUrl||stream?.webosUrl||""; playerState={stream:value?{type:"Ready",content:{...stream,url:value}}:{type:"Err",content:{message:"No direct stream"}}}; return playerState; }
export async function unloadLunoPlayer(){playerState=null;}
export function dispatchLunoPlayerAction(action,args={}){if(action==="TimeChanged"&&playerState)playerState.time=args.time||0;if(action==="Ended"&&playerState)playerState.ended=true;}
export function getReadyMetaStreams(state){const resources=Array.isArray(state?.streams)&&state.streams.length?state.streams:(Array.isArray(state?.metaStreams)?state.metaStreams:[]);return resources.flatMap(resource=>resource?.content?.type==="Ready"?(Array.isArray(resource.content.content)?resource.content.content:[]).map(stream=>({stream,request:resource.request,addon:resource.addon||null})):[]);}
export function getPlayerStreamUrl(state){if(state?.stream?.type!=="Ready")return "";const stream=state.stream.content||{};return stream.url||stream.streamingUrl||stream.externalUrl||stream.webosUrl||"";}
export async function loadLunoModel(){return null;} export async function loadBoard(){return null;} export async function loadBoardRange(){return null;} export async function searchLuno(){return null;} export async function getLunoModel(name){return name==="player"?playerState:null;} export function onLunoState(){return()=>{};} export function getLunoSourceProviders(){return listSourceProviders();}
